Repository yuwankang/FISA-Land, pull requests merged in 2024-08, with the labels that each got.

#3 feat:User Entity 추가 #1
  src/main/java/com/fisa/land/fisaland/User.java
Labels: feature

#4 feat: Add User Controller #1
  src/main/java/com/fisa/land/fisaland/common/User.java
  src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
Labels: feature

#6 market 기능
  build.gradle
  src/main/java/com/fisa/land/fisaland/FisalandApplication.java
  src/main/java/com/fisa/land/fisaland/common/BaseTimeEntity.java
  src/main/java/com/fisa/land/fisaland/market/controller/MarketReviewController.java
  src/main/java/com/fisa/land/fisaland/market/dto/MarketReviewDTO.java
  src/main/java/com/fisa/land/fisaland/market/entity/Market.java
  src/main/java/com/fisa/land/fisaland/market/entity/MarketReview.java
  src/main/java/com/fisa/land/fisaland/market/repository/MarketReviewRepository.java
  src/main/java/com/fisa/land/fisaland/market/service/MarketReviewService.java
  src/main/java/com/fisa/land/fisaland/swagger/config/SwaggerConfig.java
Labels: feature

#8 feat: User 기능 구현 #1
  src/main/java/com/example/rentalsystem/entity/LendingRecords.java
  src/main/java/com/example/rentalsystem/entity/LendingReviews.java
  src/main/java/com/fisa/fisaland/lending/controller/LendingController.java
  src/main/java/com/fisa/fisaland/lending/controller/ProductController.java
  src/main/java/com/fisa/fisaland/lending/dto/LendingRequestDto.java
  src/main/java/com/fisa/fisaland/lending/dto/ReturnRequestDto.java
  src/main/java/com/fisa/fisaland/lending/entity/LendingRecordInfo.java
  src/main/java/com/fisa/fisaland/lending/entity/LendingRecords.java
  src/main/java/com/fisa/fisaland/lending/entity/Product.java
  src/main/java/com/fisa/fisaland/lending/exception/CustomException.java
  src/main/java/com/fisa/fisaland/lending/repository/LendingRecordInfoRepository.java
  src/main/java/com/fisa/fisaland/lending/repository/LendingRecordsRepository.java
  src/main/java/com/fisa/fisaland/lending/repository/ProductRepository.java
  src/main/java/com/fisa/fisaland/lending/service/LendingService.java
  src/main/java/com/fisa/fisaland/lending/service/ProductService.java
  src/main/java/com/fisa/land/common/User.java
  src/main/java/com/fisa/land/common/UserController.java
  src/main/java/com/fisa/land/common/UserDTO.java
  src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
  src/main/java/com/fisa/land/fisaland/common/dto/LoginDTO.java
  src/main/java/com/fisa/land/fisaland/common/dto/UserDTO.java
  src/main/java/com/fisa/land/fisaland/common/entity/User.java
  src/main/java/com/fisa/land/fisaland/common/respository/UserRepository.java
  src/main/java/com/fisa/land/fisaland/common/service/UserService.java
  src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java
  src/main/java/com/fisa/land/fisaland/market/controller/MarketReviewController.java
  src/main/java/com/fisa/land/fisaland/market/dto/MarketReviewDTO.java
  src/main/java/com/fisa/land/fisaland/market/entity/Market.java
  src/main/java/com/fisa/land/fisaland/market/entity/MarketReview.java
  src/main/java/com/fisa/land/fisaland/market/repository/MarketReviewRepository.java
  src/main/java/com/fisa/land/fisaland/market/service/MarketReviewService.java
Labels: feature

#9 feat: 유저 로그인 기능 개발
  src/main/java/com/fisa/land/common/User.java
  src/main/java/com/fisa/land/common/UserController.java
  src/main/java/com/fisa/land/common/UserDTO.java
  src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
  src/main/java/com/fisa/land/fisaland/common/dto/LoginDTO.java
  src/main/java/com/fisa/land/fisaland/common/respository/UserRepository.java
  src/main/java/com/fisa/land/fisaland/common/service/UserService.java
  src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java
Labels: fix, feature

#15 feat: 유저 조회, 수정 기능 추가 issue: #1
  src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
  src/main/java/com/fisa/land/fisaland/common/dto/request/LoginDTO.java
  src/main/java/com/fisa/land/fisaland/common/dto/request/UserDTO.java
  src/main/java/com/fisa/land/fisaland/common/dto/response/UserResponseDTO.java
  src/main/java/com/fisa/land/fisaland/common/entity/User.java
  src/main/java/com/fisa/land/fisaland/common/respository/UserRepository.java
  src/main/java/com/fisa/land/fisaland/common/service/UserService.java
  src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java
Labels: feature

#17 feat: 사용자 활동 상태 컬럼 추가 및 사용자 삭제 기능 구현
  src/main/java/com/fisa/land/fisaland/common/dto/request/UserDTO.java
  src/main/java/com/fisa/land/fisaland/common/dto/response/UserResponseDTO.java
  src/main/java/com/fisa/land/fisaland/common/entity/BaseTimeEntity.java
  src/main/java/com/fisa/land/fisaland/common/entity/User.java
  src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java
  src/main/java/com/fisa/land/fisaland/market/entity/Market.java
  src/main/java/com/fisa/land/fisaland/market/entity/MarketReview.java
Labels: feature

#19 docs: 사용자 API - 스웨거 설정 추가
  src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
  src/main/java/com/fisa/land/fisaland/common/dto/request/LoginDTO.java
  src/main/java/com/fisa/land/fisaland/common/dto/request/UserDTO.java
Labels: doc

#21 refactor: 예외 처리 및 람다식으로 수정
  src/main/java/com/fisa/land/fisaland/common/entity/Product.java
  src/main/java/com/fisa/land/fisaland/common/exception/BusinessLoginException.java
  src/main/java/com/fisa/land/fisaland/common/exception/ExceptionList.java
  src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java
Labels: feature, refactor

#24 Product
  src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
  src/main/java/com/fisa/land/fisaland/lending/dto/ProductDTO.java
  src/main/java/com/fisa/land/fisaland/lending/dto/ProductResponseDTO.java
  src/main/java/com/fisa/land/fisaland/lending/entity/Product.java
  src/main/java/com/fisa/land/fisaland/lending/service/ProductService.java
  src/main/java/com/fisa/land/fisaland/lending/service/ProductServiceImpl.java
Labels: feature

#30 Product 반납, 대여 조건 추가
  src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
  src/main/java/com/fisa/land/fisaland/lending/service/ProductService.java
  src/main/java/com/fisa/land/fisaland/lending/service/ProductServiceImpl.java
Labels: feature

#31 fix : LendingRecord 업데이트 시 생성날짜와 수정날짜 동시에 업데이트 되는 문제
  src/main/java/com/fisa/land/fisaland/lending/controller/LendingReviewsController.java
  src/main/java/com/fisa/land/fisaland/lending/entity/LendingReviews.java
  src/main/java/com/fisa/land/fisaland/lending/service/LendingReviewsServiceImpl.java
Labels: fix

#33 market 관련 API
  src/main/java/com/fisa/land/fisaland/market/controller/GatheringRecordController.java
  src/main/java/com/fisa/land/fisaland/market/controller/GatheringRecordInfoController.java
  src/main/java/com/fisa/land/fisaland/market/dto/GatheringRecordDTO.java
  src/main/java/com/fisa/land/fisaland/market/dto/GatheringRecordInfoDTO.java
  src/main/java/com/fisa/land/fisaland/market/entity/GatheringRecord.java
  src/main/java/com/fisa/land/fisaland/market/entity/GatheringRecordId.java
  src/main/java/com/fisa/land/fisaland/market/entity/GatheringRecordInfo.java
  src/main/java/com/fisa/land/fisaland/market/entity/Market.java
  src/main/java/com/fisa/land/fisaland/market/repository/GatheringRecordInfoRepository.java
  src/main/java/com/fisa/land/fisaland/market/repository/GatheringRecordRepository.java
  src/main/java/com/fisa/land/fisaland/market/service/GatheringRecordInfoService.java
  src/main/java/com/fisa/land/fisaland/market/service/GatheringRecordInfoServiceImpl.java
  src/main/java/com/fisa/land/fisaland/market/service/GatheringRecordService.java
  src/main/java/com/fisa/land/fisaland/market/service/GatheringRecordServiceImpl.java
Labels: feature

#53 feat: 대여 관련 CRUD
  src/main/java/com/fisa/land/fisaland/lending/controller/LendingRecordController.java
  src/main/java/com/fisa/land/fisaland/lending/dto/LendingRecordStatusUpdateDto.java
  src/main/java/com/fisa/land/fisaland/lending/entity/LendingRecordInfo.java
  src/main/java/com/fisa/land/fisaland/lending/repository/LendingRecordRepository.java
  src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordService.java
  src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordServiceImpl.java
Labels: fix, feature

#55 fix: Lending 예외처리 및 로직 수정
  src/main/java/com/fisa/land/fisaland/common/exception/ExceptionList.java
  src/main/java/com/fisa/land/fisaland/lending/controller/LendingRecordController.java
  src/main/java/com/fisa/land/fisaland/lending/dto/LendingRecordDto.java
  src/main/java/com/fisa/land/fisaland/lending/dto/LendingRecordStatusUpdateDto.java
  src/main/java/com/fisa/land/fisaland/lending/entity/LendingRecordInfo.java
  src/main/java/com/fisa/land/fisaland/lending/repository/LendingRecordRepository.java
  src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordService.java
  src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordServiceImpl.java
Labels: fix, refactor

#58 feat: 맛집 리뷰 페이지
  src/main/resources/static/assets/css/images/overlay.png
  src/main/resources/static/assets/css/images/shadow.png
  src/main/resources/static/assets/css/main2.css
  src/main/resources/static/images/banner.jpg
  src/main/resources/static/images/pic04.jpg
  src/main/resources/static/images/pic05.jpg
  src/main/resources/static/images/pic06.jpg
  src/main/resources/static/images/pic07.jpg
  src/main/resources/static/images/pic08.jpg
  src/main/resources/static/images/pic09.jpg
  src/main/resources/static/images/pic10.jpg
  src/main/resources/static/images/shadow.png
  src/main/resources/templates/marketReview.html
Labels: feature

#62 docs&refactor: 스웨거 문서 추가 및 패키지 구조 변경
  src/main/java/com/fisa/land/fisaland/common/config/CustomServletConfig.java
  src/main/java/com/fisa/land/fisaland/common/config/LocalDateTimeFormatter.java
  src/main/java/com/fisa/land/fisaland/lending/controller/LendingRecordController.java
  src/main/java/com/fisa/land/fisaland/lending/controller/LendingReviewsController.java
  src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
  src/main/java/com/fisa/land/fisaland/market/controller/GatheringRecordController.java
  src/main/java/com/fisa/land/fisaland/market/controller/GatheringRecordInfoController.java
  src/main/java/com/fisa/land/fisaland/market/controller/MarketController.java
  src/main/java/com/fisa/land/fisaland/market/controller/MarketReviewController.java
  src/main/java/com/fisa/land/fisaland/session/SessionController.java
Labels: doc, refactor

#64 feat: 전체 리뷰 조회 페이지, 식당 조회 페이지 추가
  src/main/java/com/fisa/land/fisaland/page/MainPageController.java
  src/main/resources/static/assets/css/main2.css
  src/main/resources/static/images/food1.jpg
  src/main/resources/templates/marketReview.html
Labels: doc, feature

#65 fix: pageController 에러 해결
  src/main/java/com/fisa/land/fisaland/page/MainPageController.java
Labels: fix

#67 fix: 대여 신청시 상품 상태 업데이트
  src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordServiceImpl.java
Labels: fix

#68 fix: 반납 신청 시 product 상태 변경
  src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordServiceImpl.java
Labels: fix

#69 refactor: marketReview page refactoring
  src/main/resources/templates/marketReview.html
Labels: feature, refactor

#78 feat: AOP Common, Village 로그추출기능 추가
  build.gradle
  src/main/java/com/fisa/land/fisaland/common/aspect/UserAspect.java
  src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
  src/main/java/com/fisa/land/fisaland/lending/aspect/ErrorAspect.java
  src/main/java/com/fisa/land/fisaland/lending/aspect/LendingAspect.java
  src/main/java/com/fisa/land/fisaland/lending/aspect/OverdueAspect.java
  src/main/java/com/fisa/land/fisaland/lending/aspect/ReviewAspect.java
  src/main/java/com/fisa/land/fisaland/lending/aspect/UserActivityAspect.java
  src/main/java/com/fisa/land/fisaland/lending/controller/LendingRecordController.java
  src/main/java/com/fisa/land/fisaland/lending/controller/LendingReviewsController.java
  src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
  src/main/resources/log4j.properties
Labels: feature

#81 feat: 마켓 상세 정보 및 리뷰 페이지
  src/main/java/com/fisa/land/fisaland/lending/service/ProductServiceImpl.java
  src/main/java/com/fisa/land/fisaland/page/MainPageController.java
  src/main/resources/static/assets/css/main2.css
  src/main/resources/static/images/food2.jpg
  src/main/resources/static/images/food3.jpg
  src/main/resources/static/images/food4.jpg
  src/main/resources/static/images/food5.jpg
  src/main/resources/static/images/food6.jpg
  src/main/resources/static/images/food7.jpg
  src/main/resources/templates/index2.html
  src/main/resources/templates/marketReview.html
Labels: fix, feature

#85 feat: villageMain 수정
  src/main/resources/static/assets/css/main2.css
  src/main/resources/templates/villageMain.html
Labels: fix, feature

#86 feat: index.html logout 기능 추가
  src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
  src/main/resources/static/assets/css/main.css
  src/main/resources/templates/index.html
Labels: feature

#87 refactor: 로그인 버튼 텍스트 위치 조정
  src/main/resources/templates/login.html
Labels: fix, refactor

#91 fix: 마켓리뷰 조회 경로 수정
  src/main/java/com/fisa/land/fisaland/market/controller/MarketReviewController.java
  src/main/java/com/fisa/land/fisaland/page/MainPageController.java
  src/main/resources/templates/marketReview.html
Labels: fix

#92 feat: 연결한다
  src/main/java/com/fisa/land/fisaland/page/MainPageController.java
  src/main/resources/templates/marketList.html
  src/main/resources/templates/marketMain.html
Labels: fix, feature, help, refactor
